/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservarOkRouteImport } from './routes/reservar-ok'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppReservationsRouteImport } from './routes/_app.reservations'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRatesRouteImport } from './routes/_app.rates'
import { Route as AppExtrasRouteImport } from './routes/_app.extras'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAdminManualRouteImport } from './routes/_app.admin.manual'

const ReservarOkRoute = ReservarOkRouteImport.update({
  id: '/reservar-ok',
  path: '/reservar-ok',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRatesRoute = AppRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppRoute,
} as any)
const AppExtrasRoute = AppExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminManualRoute = AppAdminManualRouteImport.update({
  id: '/admin/manual',
  path: '/admin/manual',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/reservar-ok': typeof ReservarOkRoute
  '/calendar': typeof AppCalendarRoute
  '/customers': typeof AppCustomersRoute
  '/extras': typeof AppExtrasRoute
  '/rates': typeof AppRatesRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRoute
  '/rooms': typeof AppRoomsRoute
  '/today': typeof AppTodayRoute
  '/admin/manual': typeof AppAdminManualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/reservar-ok': typeof ReservarOkRoute
  '/calendar': typeof AppCalendarRoute
  '/customers': typeof AppCustomersRoute
  '/extras': typeof AppExtrasRoute
  '/rates': typeof AppRatesRoute
  '/reports': typeof AppReportsRoute
  '/reservations': typeof AppReservationsRoute
  '/rooms': typeof AppRoomsRoute
  '/today': typeof AppTodayRoute
  '/admin/manual': typeof AppAdminManualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/reservar-ok': typeof ReservarOkRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/extras': typeof AppExtrasRoute
  '/_app/rates': typeof AppRatesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/reservations': typeof AppReservationsRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/admin/manual': typeof AppAdminManualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reservar'
    | '/reservar-ok'
    | '/calendar'
    | '/customers'
    | '/extras'
    | '/rates'
    | '/reports'
    | '/reservations'
    | '/rooms'
    | '/today'
    | '/admin/manual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reservar'
    | '/reservar-ok'
    | '/calendar'
    | '/customers'
    | '/extras'
    | '/rates'
    | '/reports'
    | '/reservations'
    | '/rooms'
    | '/today'
    | '/admin/manual'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reservar'
    | '/reservar-ok'
    | '/_app/calendar'
    | '/_app/customers'
    | '/_app/extras'
    | '/_app/rates'
    | '/_app/reports'
    | '/_app/reservations'
    | '/_app/rooms'
    | '/_app/today'
    | '/_app/admin/manual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReservarRoute: typeof ReservarRoute
  ReservarOkRoute: typeof ReservarOkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservar-ok': {
      id: '/reservar-ok'
      path: '/reservar-ok'
      fullPath: '/reservar-ok'
      preLoaderRoute: typeof ReservarOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rates': {
      id: '/_app/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AppRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extras': {
      id: '/_app/extras'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof AppExtrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/manual': {
      id: '/_app/admin/manual'
      path: '/admin/manual'
      fullPath: '/admin/manual'
      preLoaderRoute: typeof AppAdminManualRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppExtrasRoute: typeof AppExtrasRoute
  AppRatesRoute: typeof AppRatesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppAdminManualRoute: typeof AppAdminManualRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppExtrasRoute: AppExtrasRoute,
  AppRatesRoute: AppRatesRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppTodayRoute: AppTodayRoute,
  AppAdminManualRoute: AppAdminManualRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ReservarRoute: ReservarRoute,
  ReservarOkRoute: ReservarOkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
